"""add voice sessions and agent config voice settings

Revision ID: 25745fba6f90
Revises: df46b9c0fdf6
Create Date: 2026-09-12 04:53:06.004020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25745fba6f90'
down_revision: Union[str, None] = 'df46b9c0fdf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_sessions',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_session_id', sa.String(length=255), nullable=True),
    sa.Column('provider_call_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('turn_state', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('caller_number', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('termination_reason', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('last_event_id', sa.String(length=255), nullable=True),
    sa.Column('last_event_result', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_call_id', name='uq_voice_session_provider_call')
    )
    op.create_index(op.f('ix_voice_sessions_college_id'), 'voice_sessions', ['college_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_conversation_id'), 'voice_sessions', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_voice_sessions_provider_call_id'), 'voice_sessions', ['provider_call_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_provider_session_id'), 'voice_sessions', ['provider_session_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_status'), 'voice_sessions', ['status'], unique=False)
    op.add_column('agent_configs', sa.Column('voice_phone_number', sa.String(length=30), nullable=True))
    op.add_column('agent_configs', sa.Column('voice_settings', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_agent_configs_voice_phone_number'), 'agent_configs', ['voice_phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_configs_voice_phone_number'), table_name='agent_configs')
    op.drop_column('agent_configs', 'voice_settings')
    op.drop_column('agent_configs', 'voice_phone_number')
    op.drop_index(op.f('ix_voice_sessions_status'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_provider_session_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_provider_call_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_conversation_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_college_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    # ### end Alembic commands ###
