"""add unanswered questions

Revision ID: 2d3cef3d2f39
Revises: bffda9472def
Create Date: 2026-09-12 01:14:28.463579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3cef3d2f39'
down_revision: Union[str, None] = 'bffda9472def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unanswered_questions',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unanswered_questions_college_id'), 'unanswered_questions', ['college_id'], unique=False)
    op.create_index(op.f('ix_unanswered_questions_created_at'), 'unanswered_questions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unanswered_questions_created_at'), table_name='unanswered_questions')
    op.drop_index(op.f('ix_unanswered_questions_college_id'), table_name='unanswered_questions')
    op.drop_table('unanswered_questions')
    # ### end Alembic commands ###
