"""add appointment cancellation reason

Revision ID: 53dd1a231cdb
Revises: 873674a6f405
Create Date: 2026-09-12 03:59:09.735093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dd1a231cdb'
down_revision: Union[str, None] = '873674a6f405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'cancellation_reason')
    # ### end Alembic commands ###
