"""add analytics composite indexes

Revision ID: 697de9da1bff
Revises: 25745fba6f90
Create Date: 2026-09-12 11:34:48.844182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697de9da1bff'
down_revision: Union[str, None] = '25745fba6f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_applications_college_created', 'applications', ['college_id', 'created_at'], unique=False)
    op.create_index('ix_appointments_college_created', 'appointments', ['college_id', 'created_at'], unique=False)
    op.create_index('ix_conversations_college_created', 'conversations', ['college_id', 'created_at'], unique=False)
    op.create_index('ix_leads_college_created', 'leads', ['college_id', 'created_at'], unique=False)
    op.create_index('ix_messages_college_created', 'messages', ['college_id', 'created_at'], unique=False)
    op.create_index('ix_support_tickets_college_created', 'support_tickets', ['college_id', 'created_at'], unique=False)
    op.create_index('ix_voice_sessions_college_created', 'voice_sessions', ['college_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voice_sessions_college_created', table_name='voice_sessions')
    op.drop_index('ix_support_tickets_college_created', table_name='support_tickets')
    op.drop_index('ix_messages_college_created', table_name='messages')
    op.drop_index('ix_leads_college_created', table_name='leads')
    op.drop_index('ix_conversations_college_created', table_name='conversations')
    op.drop_index('ix_appointments_college_created', table_name='appointments')
    op.drop_index('ix_applications_college_created', table_name='applications')
    # ### end Alembic commands ###
