"""add lead score event idempotency key

Revision ID: 873674a6f405
Revises: 2d3cef3d2f39
Create Date: 2026-09-12 02:25:46.506552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873674a6f405'
down_revision: Union[str, None] = '2d3cef3d2f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_score_events', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('lead_score_events', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_lead_score_events_idempotency_key'), 'lead_score_events', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_score_events_idempotency_key'), table_name='lead_score_events')
    op.drop_column('lead_score_events', 'idempotency_key')
    op.drop_column('lead_score_events', 'source')
    # ### end Alembic commands ###
