"""add support ticket idempotency key

Revision ID: df46b9c0fdf6
Revises: 53dd1a231cdb
Create Date: 2026-09-12 04:31:57.548526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df46b9c0fdf6'
down_revision: Union[str, None] = '53dd1a231cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_support_tickets_idempotency_key'), 'support_tickets', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_idempotency_key'), table_name='support_tickets')
    op.drop_column('support_tickets', 'idempotency_key')
    # ### end Alembic commands ###
