"""make appointment slot uniqueness apply only to scheduled appointments

Revision ID: eaa7312f868f
Revises: 697de9da1bff
Create Date: 2026-09-13 03:27:37.335597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa7312f868f'
down_revision: Union[str, None] = '697de9da1bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_appointment_counselor_start_time'), 'appointments', type_='unique')
    op.create_index('uq_appointment_counselor_start_time_active', 'appointments', ['counselor_id', 'start_time'], unique=True, postgresql_where=sa.text("status = 'scheduled'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointment_counselor_start_time_active', table_name='appointments', postgresql_where=sa.text("status = 'scheduled'"))
    op.create_unique_constraint(op.f('uq_appointment_counselor_start_time'), 'appointments', ['counselor_id', 'start_time'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
